# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
