# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_review_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_title',
        ),
    ]
