# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_review_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_title',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book_app.Book'),
            preserve_default=False,
        ),
    ]
